function res = polmatern(rvect,u,v,a,nu)
%% polmatern(r,u,v,a,nu)
%% cov correp to ((w+u)^2+v^2) ((w-u)^2+v^2) / (a^2+w^2)^(nu+1+2)

p0=(2*a^4 + 2*a^2*nu*(-u^2 + v^2) + nu*(1 + nu)*(u^2 + v^2)^2) / ...
    (2.*a^(2*(2 + nu))*nu*(1 + nu)*(2 + nu));

indnonz = find(rvect>0);
indzeros = find(rvect==0);
r = rvect(indnonz);
res = rvect;

res(indnonz) = ...
besselk(nu,a*r) .*  ...
 (  (r/a).^nu / (2^nu*gamma(1 + nu)) + ...
    (2^(-2 - nu)*(r/a).^(2 + nu)*(a^4 + 2*a^2*u^2 + u^4 - 2*a^2*v^2 + ...
                                 2*u^2*v^2 + v^4))/ gamma(3 + nu)  ...  
  ) + ...
besselk(1 + nu,a*r) .* ...
    ( ((r/a).^(1 + nu)*(-a^2 - u^2 + v^2)) / (2^nu*gamma(2 + nu)) + ...
      ( 2^(-1 - nu)*(1 + nu)*(r/a).^(2 + nu)* ...
       (a^4 + 2*a^2*u^2 + u^4 - 2*a^2*v^2 + 2*u^2*v^2 + v^4)  )./ ...
       (a*r*gamma(3 + nu)) ...
    );

res(indnonz) = res(indnonz)/p0;
res(indzeros)=1;
